"""Summarization middleware — compresses long conversation histories."""

from __future__ import annotations

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage

from mr_lang.core.state import AgentState
from mr_lang.middleware.base import BaseMiddleware

_SUMMARY_PROMPT = (
    "You are a conversation summarizer. Condense the following messages into a "
    "brief, factual summary that preserves all key information, decisions, and "
    "context needed to continue the conversation. Respond with ONLY the summary."
)


class SummarizationMiddleware(BaseMiddleware):
    """Summarize older messages when conversation length exceeds a threshold.

    When ``len(state['messages'])`` exceeds *threshold*, all messages except
    the most recent *keep_recent* are replaced with a single summary message
    generated by the supplied model.

    Parameters
    ----------
    model:
        Chat model used to generate the summary.
    threshold:
        Message count that triggers summarization (default 20).
    keep_recent:
        Number of recent messages to preserve verbatim (default 4).
    """

    def __init__(
        self,
        model: BaseChatModel,
        threshold: int = 20,
        keep_recent: int = 4,
    ) -> None:
        self._model = model
        self._threshold = threshold
        self._keep_recent = keep_recent

    async def before_model(self, state: AgentState) -> AgentState:
        messages = state.get("messages", [])

        if len(messages) <= self._threshold:
            return state

        old_messages = messages[: -self._keep_recent]
        recent_messages = messages[-self._keep_recent :]

        # Build a summarization request
        formatted = "\n".join(
            f"{getattr(m, 'type', 'unknown')}: {m.content}"
            for m in old_messages
            if hasattr(m, "content") and m.content
        )

        summary_response = await self._model.ainvoke(
            [
                SystemMessage(content=_SUMMARY_PROMPT),
                HumanMessage(content=formatted),
            ]
        )

        summary_msg = SystemMessage(content=f"[Conversation summary]\n{summary_response.content}")

        return {
            **state,
            "messages": [summary_msg, *recent_messages],
        }

    async def after_model(self, state: AgentState, response: BaseMessage) -> BaseMessage:
        return response
